[package]
name = "md-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.24.0", default-features = true, features = ["macros", "all-widgets"] }
regex = "1.10.2"
