[package]
name = "md-cli"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[dependencies]
better-panic = "0.3.0"
crossterm = "0.27.0"
itertools = "0.12.0"
open = "5.0.1"
pest = "2.7.5"
pest_derive = "2.7.5"
ratatui = { version = "0.25.0", default-features = true, features = ["macros", "all-widgets"] }
strsim = "0.10.0"
