[package]
name = "md-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
itertools = "0.12.0"
pest = "2.7.5"
pest_derive = "2.7.5"
ratatui = { version = "0.24.0", default-features = true, features = ["macros", "all-widgets"] }
