[package]
name = "md-tui"
version = "0.1.0"
edition = "2021"
authors = ["Henrik Tøn Løvhaug"]
description = "A terminal markdown viewer"
readme = "README.md"
license = "AGPL-3.0-or-later"
repository = "https://github.com/henriklovhaug/md-tui"
homepage = "https://github.com/henriklovhaug/md-tui"
keywords = ["markdown", "terminal", "viewer", "tui"]

[[bin]]
name = "mdt"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[dependencies]
better-panic = "0.3.0"
crossterm = "0.27.0"
itertools = "0.12.1"
open = "5.0.1"
pest = "2.7.7"
pest_derive = "2.7.7"
ratatui = { version = "0.26.1", default-features = true, features = ["macros", "all-widgets"] }
strsim = "0.11.0"
